{{- if and .Values.issuer.enabled .Values.issuer.cluster }}
{{- if hasKey .Values "extraDomains" }}
{{- $secretName := .Values.secretName }}
{{- $region := .Values.jxRequirements.cluster.region }}
{{- $provider := .Values.jxRequirements.cluster.provider }}
{{- $project := .Values.jxRequirements.cluster.project }}
{{- $azure := .Values.jxRequirements.cluster.azure }}
{{- range $key, $val := .Values.extraDomains }}
{{- if $val.tls.enabled}}
{{- if $val.tls.production }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $val.domain | replace "." "-" }}-prod-extra
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ $val.tls.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-{{ $val.domain | replace "." "-" }}-prod-extra
    solvers:
    - selector:
        dnsNames:
        - "*.{{ $val.domain }}"
        - "{{ $val.domain }}"
        # ACME DNS-01 provider configurations
      dns01:
{{- if eq $provider "gke" }}
        cloudDNS:
          # The project in which to update the DNS zone
          project: "{{ .Values.jxRequirements.cluster.project }}"
{{- if $secretName }}
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            name: {{ $secretName }}
            key: credentials.json
{{- end }}
{{- end }}
{{- if eq $provider "eks" }}
        route53:
          region: {{ $region }}
{{- end }}
{{- if eq $provider "aks" }}
        azureDNS:
          subscriptionID: {{ $azure.dns.subscriptionId }}
          resourceGroupName: {{ $azure.dns.resourceGroup }}
          hostedZoneName: {{ $val.domain }}
          managedIdentity:
            clientID: {{ $azure.clusterNodes.clientID }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
