apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/helm/release.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
              name: ""
              resources: {}
            - name: next-version
              resources: {}
            - name: jx-variables
              resources: {}
            - image: ghcr.io/jenkins-x/jx-boot:3.10.118
              name: promote-changelog
              resources: {}
              script: |
                #!/usr/bin/env sh
                source /workspace/source/.jx/variables.sh
                if [ -d "/workspace/source/charts/$REPO_NAME" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
                else echo no charts; fi
                if [ -d "/workspace/source/charts/$REPO_NAME" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
                else echo no charts; fi
                if [ -d "/workspace/source/charts/acme-certificates" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/acme-certificates/Chart.yaml
                else echo no charts; fi
                if [ -d "/workspace/source/charts/acme-nonereqs" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/acme-nonereqs/Chart.yaml
                else echo no charts; fi
                if [ -d "/workspace/source/charts/acme-certificates-nonereqs" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/acme-certificates-nonereqs/Chart.yaml
                else echo no charts; fi
                git commit -a -m "chore: release $VERSION" --allow-empty
                git tag -fa v$VERSION -m "Release version $VERSION"
                git push origin v$VERSION
                jx changelog create --version v${VERSION}
            - name: promote-helm-release
              resources: {}
            - name: promote-jx-promote
              resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
