apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    trigger: "/test"
    rerun_command: "/retest"
    source: "pullrequest.yaml"
  - name: lint-pipelines
    context: "lint-pipelines"
    run_if_changed: '.lighthouse\/jenkins-x\/.*'
    optional: false
    trigger: (?m)^/test( all| lint-pipelines.*),?(s+|$)
    rerun_command: /test lint-pipelines
    source: "lint-pipelines.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
